import 'bootstrap/dist/css/bootstrap.min.css';
import { Inter } from 'next/font/google';
import Navbarr from '@/components/navbarr';
import Container from 'react-bootstrap/Container';
import Footer from '@/components/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Container fluid>
					<Navbarr />
					{children}
				</Container>
				<Footer />
			</body>
		</html>
	);
}
