# Generated by Django 5.0.3 on 2024-04-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_company_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shop_name',
            new_name='shop',
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
