# Generated by Django 5.0.3 on 2024-04-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_shop_name_product_shop_alter_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shop',
            new_name='product_shop',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='status',
            new_name='product_status',
        ),
        migrations.AlterField(
            model_name='container',
            name='capacity',
            field=models.IntegerField(help_text='in ml'),
        ),
    ]
