# Generated by Django 5.0.3 on 2024-04-04 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_shop_product_product_shop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_shop',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_status',
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_shop', to='products.company'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_status', to='products.status'),
        ),
    ]
